version:  '3.7'
services:
  app:
      image: kushnerroman/household:0.0.2
      ports:
        - "8080:8080"
      environment:
        - SPRING_PROFILES_ACTIVE=dev
        - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/shared?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=admin
      depends_on:
        - db
  db:
        image: mysql:8.0.27
        environment:
            - DATABASE_HOST=docker-mysql
            - DATABASE_PORT=3306
            - MYSQL_DATABASE=shared
            - MYSQL_ROOT_PASSWORD=admin
